# Generated by Django 2.1.7 on 2019-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('superClassSeat', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('seatNo', models.CharField(max_length=5)),
                ('movieTitle', models.CharField(max_length=64)),
                ('ticketCreateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
